### ISSUE TITLE
machine learning for neuroimaging

### ISSUE THREAD

**Issue by pbellec** [brainhackorg/school#105]
this module needs to be updated:
https://school.brainhackmtl.org/modules/machine_learning_neuroimaging/

I suggest to switch to the MAIN resources:
https://main-educational.github.io/intro_ML/intro.html

**Comment by me-pic** [comment]
Just to make sure. You want to change the content of the exercises for the MAIN resources (or something similar). Or you want to change completely the section "Resources" section to point to the MAIN tutorial ?

**Comment by pbellec** [comment]
I'd adapt both, but Andreanne had worked from the previous iteration of the MAIN tutorial so there should not be any major change.
