### ISSUE TITLE
functional connectivity

### ISSUE THREAD

**Issue by pbellec** [brainhackorg/school#106]
this module needs updating: https://school.brainhackmtl.org/modules/fmri_connectivity/

I suggest to add this resource (in French unfortunately at the moment): https://psy3018.github.io/connectivite.html

we could also list the relevant tutorials from nilearn: https://nilearn.github.io/stable/user_guide.html

maybe also update the exercises and make sure they incorporate https://nilearn.github.io/dev/modules/generated/nilearn.interfaces.fmriprep.load_confounds.html

**Comment by dllussier** [comment]
Updated index.md #115 
- Edited resources
- Added additional resources
- Changed instructor name
- Edited links
