### ISSUE TITLE
update the module on git and github

### ISSUE THREAD

**Issue by pbellec** [brainhackorg/school#85]
page: https://school.brainhackmtl.org/modules/git_github/
code: https://github.com/brainhackorg/school/tree/master/content/en/modules/git_github

Should integrate this new resource: https://learngitbranching.js.org/

**Comment by pbellec** [comment]
this is also a great resource: https://the-turing-way.netlify.app/collaboration/github-novice.html

**Comment by complexbrains** [comment]
ok I am on it!

**Comment by complexbrains** [comment]
btw I didn't change your name as the module representation but if you would like me to take over it I am happy to do so!

**Comment by pbellec** [comment]
I've added you as the contact person, thanks!
